# Generated by Django 4.1.2 on 2022-12-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datingpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date_category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DateCategory',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
